USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=Disable802.1xAutomaticConnection
VERSION=1.1
PACKAGE_VERSION=$(VERSION)
REVERSE_DOMAIN=org.povertyactionlab


PAYLOAD=\
		pack-Library-LaunchAgents-org.povertyactionlab.disable8021xAutomaticConnection.plist\
		pack-usr-local-bin-disable8021xAutomaticConnection.sh\
		pack-script-postinstall
