USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=disable_802.1x_Automatic_Connection
VERSION=1.0
REVERSE_DOMAIN=org.povertyactionlab


PAYLOAD=\
		pack-Library-LaunchAgents-org.povertyactionlab.disable8021xAutomaticConnection.plist\
		pack-usr-local-bin-disable8021xAutomaticConnection.sh\
		pack-script-postinstall
